# Generated by Django 5.1.7 on 2025-03-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='github_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
